# See https://wiki.hyprland.org/Configuring/Keywords/ for more
exec-once = waybar & ~/.config/hypr/startup.sh

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun
$logout = kitty -e loginctl lock-session $XDG_SESSION_ID

